### PR TITLE
Add minimal CI (based on free-of-cost GitHub Actions)

### PR DESCRIPTION
**Pull request by hartwork**
This will make sure that the build never breaks unnoticed again. What do you think?

PS: For the current build logs and what to expect, page https://github.com/hartwork/color-oracle-java/actions may be of interest.

### CODE REVIEW

**Comment by nvkelso** [comment]
@berniejenny ?

**Comment by hartwork** [comment]
@berniejenny @nvkelso any news? I'm happy to answer questions about this if anything is unclear, on or offline, mail or videocall. I'm using a close-to-identical CI setup in multiple other projects happily, and they are a great time saver and safety net. One such project is https://github.com/git-big-picture/git-big-picture/tree/master/.github .

What does it take to get some version of this merged? I'm happy to extend the readme with how to compile color-oracle-java from source on Ubuntu, once this PR here is integrated.

**Comment by hartwork** [comment]
Please please :smiley:

**Comment by nvkelso** [comment]
LGTM

**Comment by nvkelso** [comment]
Thanks!

**Pull request merged**
